export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";
export const ADD_ANSWER_REQUEST = "ADD_ANSWER_REQUEST";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAIL = "ADD_ANSWER_FAIL";

export const VOTE_QUESTION_REQUEST = "VOTE_QUESTION_REQUEST";
export const VOTE_QUESTION_SUCCESS = "VOTE_QUESTION_SUCCESS";
export const VOTE_QUESTION_FAIL = "VOTE_QUESTION_FAIL";
export const GET_ALL_QUESTION_REQUEST = "GET_ALL_QUESTION_REQUEST";
export const GET_ALL_QUESTION_SUCCESS = "GET_ALL_QUESTION_SUCCESS";
export const GET_ALL_QUESTION_FAIL = "GET_ALL_QUESTION_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
