export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOAD_ALL_USER_REQUEST = "LOAD_ALL_USER_REQUEST";
export const LOAD_ALL_USER_SUCCESS = "LOAD_ALL_USER_SUCCESS";
export const LOAD_ALL_USER_FAIL = "LOAD_ALL_USER_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
